[2023-06-07T18:07:52.991+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:07:53.008+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:07:53.008+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:07:53.045+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 03:00:00+00:00
[2023-06-07T18:07:53.070+0300] {standard_task_runner.py:57} INFO - Started process 38189 to run task
[2023-06-07T18:07:53.084+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T03:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmp3ko8_j4i']
[2023-06-07T18:07:53.098+0300] {standard_task_runner.py:85} INFO - Job 148: Subtask get_data
[2023-06-07T18:07:53.306+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:07:53.576+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T03:00:00+00:00'
[2023-06-07T18:07:54.601+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:07:54.840+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230606T030000, start_date=20230607T150752, end_date=20230607T150754
[2023-06-07T18:07:54.919+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 148 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 38189)
[2023-06-07T18:07:54.957+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:07:55.022+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:44:53.425+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:44:53.457+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:44:53.458+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:44:53.529+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 03:00:00+00:00
[2023-06-07T18:44:53.536+0300] {standard_task_runner.py:57} INFO - Started process 52967 to run task
[2023-06-07T18:44:53.550+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T03:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmphceskkqu']
[2023-06-07T18:44:53.554+0300] {standard_task_runner.py:85} INFO - Job 216: Subtask get_data
[2023-06-07T18:44:53.752+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:44:54.364+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T03:00:00+00:00'
[2023-06-07T18:44:54.365+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:44:54.400+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T030000, start_date=20230607T154453, end_date=20230607T154454
[2023-06-07T18:44:54.449+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:44:54.494+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:50:11.611+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:50:11.675+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [queued]>
[2023-06-07T18:50:11.675+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:50:11.811+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-06 03:00:00+00:00
[2023-06-07T18:50:11.862+0300] {standard_task_runner.py:57} INFO - Started process 57390 to run task
[2023-06-07T18:50:11.902+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-06T03:00:00+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpl57139ib']
[2023-06-07T18:50:11.915+0300] {standard_task_runner.py:85} INFO - Job 281: Subtask get_data
[2023-06-07T18:50:12.545+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-06T03:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:50:13.113+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-06T03:00:00+00:00'
[2023-06-07T18:50:13.113+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:50:13.157+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230606T030000, start_date=20230607T155011, end_date=20230607T155013
[2023-06-07T18:50:13.215+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:50:13.256+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
