[2023-06-07T18:08:21.866+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:08:21.880+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:08:21.880+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:08:22.042+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 13:00:00+00:00
[2023-06-07T18:08:22.048+0300] {standard_task_runner.py:57} INFO - Started process 39902 to run task
[2023-06-07T18:08:22.057+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T13:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmponuhdimc']
[2023-06-07T18:08:22.061+0300] {standard_task_runner.py:85} INFO - Job 182: Subtask get_data
[2023-06-07T18:08:22.185+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:08:22.350+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T13:00:00+00:00'
[2023-06-07T18:08:33.689+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:33.830+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230607T130000, start_date=20230607T150821, end_date=20230607T150833
[2023-06-07T18:08:33.854+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 182 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 39902)
[2023-06-07T18:08:33.868+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:33.894+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:45:15.691+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:45:15.749+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:45:15.749+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:45:15.803+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 13:00:00+00:00
[2023-06-07T18:45:15.809+0300] {standard_task_runner.py:57} INFO - Started process 54297 to run task
[2023-06-07T18:45:15.820+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T13:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpp21bhebj']
[2023-06-07T18:45:15.826+0300] {standard_task_runner.py:85} INFO - Job 250: Subtask get_data
[2023-06-07T18:45:16.054+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:45:16.411+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T13:00:00+00:00'
[2023-06-07T18:45:16.411+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:45:16.436+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230607T130000, start_date=20230607T154515, end_date=20230607T154516
[2023-06-07T18:45:16.472+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:45:16.506+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:50:35.486+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:50:35.529+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [queued]>
[2023-06-07T18:50:35.529+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:50:35.613+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 13:00:00+00:00
[2023-06-07T18:50:35.619+0300] {standard_task_runner.py:57} INFO - Started process 58671 to run task
[2023-06-07T18:50:35.626+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T13:00:00+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpcr53b9zh']
[2023-06-07T18:50:35.633+0300] {standard_task_runner.py:85} INFO - Job 315: Subtask get_data
[2023-06-07T18:50:35.773+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T13:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:50:36.099+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T13:00:00+00:00'
[2023-06-07T18:50:36.099+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:50:36.130+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230607T130000, start_date=20230607T155035, end_date=20230607T155036
[2023-06-07T18:50:36.209+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:50:36.250+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
