[2023-06-07T18:08:21.327+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:08:21.342+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:08:21.343+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:08:21.452+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 11:00:00+00:00
[2023-06-07T18:08:21.458+0300] {standard_task_runner.py:57} INFO - Started process 39874 to run task
[2023-06-07T18:08:21.473+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T11:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmpdh209nni']
[2023-06-07T18:08:21.477+0300] {standard_task_runner.py:85} INFO - Job 180: Subtask get_data
[2023-06-07T18:08:21.623+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:08:21.839+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T11:00:00+00:00'
[2023-06-07T18:08:30.747+0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/mutwiri/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mutwiri/airflow/dags/templating_using_python.py", line 20, in _get_data
    request.urlretrieve(url, output_path)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
[2023-06-07T18:08:30.912+0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stocksense, task_id=get_data, execution_date=20230607T110000, start_date=20230607T150821, end_date=20230607T150830
[2023-06-07T18:08:30.931+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 180 for task get_data (HTTP Error 503: Service Temporarily Unavailable; 39874)
[2023-06-07T18:08:30.945+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-07T18:08:30.972+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:45:14.880+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:45:14.941+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:45:14.942+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:45:14.993+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 11:00:00+00:00
[2023-06-07T18:45:14.998+0300] {standard_task_runner.py:57} INFO - Started process 54261 to run task
[2023-06-07T18:45:15.015+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T11:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmph3b361g7']
[2023-06-07T18:45:15.020+0300] {standard_task_runner.py:85} INFO - Job 248: Subtask get_data
[2023-06-07T18:45:15.309+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:45:15.907+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T11:00:00+00:00'
[2023-06-07T18:45:15.915+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:45:15.984+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230607T110000, start_date=20230607T154514, end_date=20230607T154515
[2023-06-07T18:45:16.084+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:45:16.138+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-07T18:50:34.860+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:50:34.900+0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [queued]>
[2023-06-07T18:50:34.901+0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-07T18:50:35.005+0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data> on 2023-06-07 11:00:00+00:00
[2023-06-07T18:50:35.015+0300] {standard_task_runner.py:57} INFO - Started process 58596 to run task
[2023-06-07T18:50:35.039+0300] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stocksense', 'get_data', 'scheduled__2023-06-07T11:00:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/templating_using_python.py', '--cfg-path', '/tmp/tmp9o60a4mz']
[2023-06-07T18:50:35.053+0300] {standard_task_runner.py:85} INFO - Job 313: Subtask get_data
[2023-06-07T18:50:35.246+0300] {task_command.py:410} INFO - Running <TaskInstance: stocksense.get_data scheduled__2023-06-07T11:00:00+00:00 [running]> on host mutwiri
[2023-06-07T18:50:35.711+0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stocksense' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T11:00:00+00:00'
[2023-06-07T18:50:35.712+0300] {python.py:183} INFO - Done. Returned value was: None
[2023-06-07T18:50:35.745+0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=stocksense, task_id=get_data, execution_date=20230607T110000, start_date=20230607T155034, end_date=20230607T155035
[2023-06-07T18:50:35.785+0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-07T18:50:35.830+0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
